In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from PIL import Image
import os

# Disasternet

In [2]:
data = pd.read_csv("data/disasterDataset/datasetDisaster/dataset_curate1.csv")  
# data = fix_paths(data)

corrupt_images = []

for idx, row in data.iterrows():
    img_path = row['image_path']
    img_path = os.path.join("data/disasterDataset/", img_path).replace("\\", "/")
    if not os.path.exists(img_path):
        print(f"No existe: {img_path}")
    try:
        with Image.open(img_path) as img:
            img.verify()  
    except Exception as e:
        print(f"Corrupt image: {img_path} -> {e}")
        corrupt_images.append(img_path)

print(f"\nTotal de imágenes corruptas: {len(corrupt_images)}")

Total de imágenes corruptas: 0

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3782 entries, 0 to 3781
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   labels           3782 non-null   object
 1   image_path       3782 non-null   object
 2   post_text        3782 non-null   object
 3   row_id           3782 non-null   int64
 4   langdetect_lang  3782 non-null   object
dtypes: int64(1), object(4)
memory usage: 147.9+ KB

In [4]:
data.columns
data['enc_label'] = data['labels'].replace({'flood':0,'huaico':1,'landslide':2,
                                            'forest fire':3,'frost hail':4,'lightning storm':5 , 'drought':6})
data["enc_label"].value_counts()

/tmp/ipykernel_609002/419919481.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['enc_label'] = data['labels'].replace({'flood':0,'huaico':1,'landslide':2,

enc_label
0    748
2    652
1    646
3    541
5    411
6    397
4    387
Name: count, dtype: int64

In [5]:
data_path = "data/disasterDataset/"
data["image_path"] = data["image_path"].apply(
    lambda x: os.path.join(data_path, x).replace("\\", "/")
)
data.head()

,labels,image_path,post_text,row_id,langdetect_lang,enc_label
0,flood,data/disasterDataset/dataset/enchente/2013a96b...,Meu Deus imagino como será no forte do ...,0,pt,0
1,flood,data/disasterDataset/dataset/enchente/5f21ba38...,URUGUAIANA DEBAIXO D’ÁGUA | Chuva extrema em c...,1,pt,0
2,flood,data/disasterDataset/dataset/enchente/43e80036...,VÍDEO: A forte chuva que atingiu Canoas nesta ...,2,pt,0
3,flood,data/disasterDataset/dataset/enchente/f0955e19...,"Meio rio, meio lago... Um dos locais mais afet...",3,pt,0
4,flood,data/disasterDataset/dataset/enchente/4dcc39e3...,"Ondas altas, com até 4 metros, causadas por um...",4,pt,0

In [6]:
train_data, test_data = train_test_split(data, test_size=0.2, random_state=42)
train_df, val_data =  train_test_split(train_data, test_size=0.1, random_state=42)

In [7]:
train_df.to_csv("data/disasterDataset/datasetDisaster/train_data.csv", index=False)
val_data.to_csv("data/disasterDataset/datasetDisaster/val_data.csv", index=False)
test_data.to_csv("data/disasterDataset/datasetDisaster/test_data.csv", index=False)

In [8]:
train_data= pd.read_csv("data/disasterDataset/datasetDisaster/train_data.csv")
test_data= pd.read_csv("data/disasterDataset/datasetDisaster/test_data.csv")
val_data= pd.read_csv("data/disasterDataset/datasetDisaster/val_data.csv")

In [9]:
train_data.head()

,labels,image_path,post_text,row_id,langdetect_lang,enc_label
0,huaico,data/disasterDataset/dataset/huaico/781e77ab92...,CÉSAR ACUÑA ENTREGÓ DINERO EN EFECTIVO A DAMNI...,552,es,1
1,lightning storm,data/disasterDataset/dataset/tempestade_rayo/b...,Está acontecendo sequestros relâmpagos em Sant...,1155,pt,5
2,landslide,data/disasterDataset/dataset/deslizamento_de_t...,CONTINÚA BLOQUEADA LA CARRETERA HUANCAYO - AYA...,1291,es,2
3,flood,data/disasterDataset/dataset/enchente/6d39146c...,Via Brasil de Fato RS DESASTRE CLIMÁTICO D...,202,pt,0
4,landslide,data/disasterDataset/dataset/deslizamento_de_t...,DESLIZAMIENTOS AFECTAN EL TRÁNSITO EN LA CARRE...,1299,es,2

In [9]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 757 entries, 0 to 756
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   labels           757 non-null    object
 1   image_path       757 non-null    object
 2   post_text        757 non-null    object
 3   row_id           757 non-null    int64
 4   langdetect_lang  757 non-null    object
 5   enc_label        757 non-null    int64
dtypes: int64(2), object(4)
memory usage: 35.6+ KB

In [10]:
val_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   labels           303 non-null    object
 1   image_path       303 non-null    object
 2   post_text        303 non-null    object
 3   row_id           303 non-null    int64
 4   langdetect_lang  303 non-null    object
 5   enc_label        303 non-null    int64
dtypes: int64(2), object(4)
memory usage: 14.3+ KB

In [ ]:
data_path = "data/disasterDataset/"
train_img_path = data_path + train_data['image_path']
val_img_path = data_path + val_data['image_path']
test_img_path = data_path + test_data['image_path']

0    data/disasterDataset/dataset\huaico\fc353991d1...
1    data/disasterDataset/dataset\seca\5dca461541b1...
2    data/disasterDataset/dataset\deslizamento_de_t...
3    data/disasterDataset/dataset\deslizamento_de_t...
4    data/disasterDataset/dataset\deslizamento_de_t...
Name: image_path, dtype: object

In [11]:
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.applications.vgg16 import preprocess_input
from PIL import ImageFile
import numpy as np

def get_input(path):
    ImageFile.LOAD_TRUNCATED_IMAGES = True
    img = load_img(path, target_size=(150,150))
    return img


# Takes in image and preprocess it
def process_input(img):
    img_data = img_to_array(img)        
    img_data = np.expand_dims(img_data, axis=0) 
    img_data = preprocess_input(img_data)     
    return img_data

ModuleNotFoundError: No module named 'tensorflow'

In [12]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

encoder=OneHotEncoder(sparse_output=False)
encoded_labels = pd.DataFrame (encoder.fit_transform(train_data[['labels']]))
encoded_labels .columns = encoder.get_feature_names_out(['labels'])
train_data= pd.concat([train_data, encoded_labels ], axis=1)

train_data.head()

,labels,image_path,post_text,row_id,langdetect_lang,enc_label,labels_drought,labels_flood,labels_forest fire,labels_frost hail,labels_huaico,labels_landslide,labels_lightning storm
0,huaico,dataset\huaico\781e77ab92ccc5305590f462cadb016...,CÉSAR ACUÑA ENTREGÓ DINERO EN EFECTIVO A DAMNI...,552,es,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,lightning storm,dataset\tempestade_rayo\bcd8d98c938ea9a990e951...,Está acontecendo sequestros relâmpagos em Sant...,1155,pt,5,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,landslide,dataset\deslizamento_de_terra\672fdfd5cfdd1e6c...,CONTINÚA BLOQUEADA LA CARRETERA HUANCAYO - AYA...,1291,es,2,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,flood,dataset\enchente\6d39146cf49bcd21739cdf33a88ae...,Via Brasil de Fato RS DESASTRE CLIMÁTICO D...,202,pt,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,landslide,dataset\deslizamento_de_terra\3fb8820520bcf975...,DESLIZAMIENTOS AFECTAN EL TRÁNSITO EN LA CARRE...,1299,es,2,0.0,0.0,0.0,0.0,0.0,1.0,0.0

# DamageDataset

In [10]:
dt = pd.read_csv("data/damage_dataset/dataset.csv")
dt.head()

data_path = "data/damage_dataset"

In [11]:
dt["image_path"] = dt["image_path"].str.replace("^dataset/", "", regex=True)
dt.head()

,label,image_path,post_text
0,fires,fires/images/forrestfire_2016-04-27_23-31-08.jpg,#fire #tornado #firetornado #forrestfire
1,fires,fires/images/buildingfire_2017-11-18_00-22-43.jpg,"Apartment fire in Harlem, NYC. \n#newyorkcity ..."
2,fires,fires/images/forrestfire_2016-07-18_09-31-45.jpg,Forrest fires=emergency runs to Wyoming to get...
3,fires,fires/images/buildingfire_2016-07-20_14-36-11.jpg,Glowing tin on the side of a garden shed at a ...
4,fires,fires/images/buildingfire_2016-12-12_22-50-08.jpg,My building is on fire.\n#mydubai\n#palmjumeir...

In [12]:
def corrupt_images(path, data):
    corrupt_images = []

    for idx, row in data.iterrows():
        img_path = row['image_path']
        img_path = os.path.join(path, img_path).replace("\\", "/")
        if not os.path.exists(img_path):
            print(f"No existe: {img_path}")
        try:
            with Image.open(img_path) as img:
                img.verify()  
        except Exception as e:
            print(f"Corrupt image: {img_path} -> {e}")
            corrupt_images.append(img_path)

    print(f"\nTotal de imágenes corruptas: {len(corrupt_images)}")

corrupt_images(data_path,dt)

Total de imágenes corruptas: 0

In [13]:
dt['label'].value_counts()

label
non_damage                2972
damaged_infrastructure    1418
damaged_nature             515
flood                      385
fires                      349
human_damage               240
Name: count, dtype: int64

In [14]:
dt.columns
dt['enc_label'] = dt['label'].replace({'non_damage':0,'damaged_infrastructure':1,'damaged_nature':2,
                                            'flood':3,'fires':4,'human_damage':5})
dt["enc_label"].value_counts()

/tmp/ipykernel_609002/87745440.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dt['enc_label'] = dt['label'].replace({'non_damage':0,'damaged_infrastructure':1,'damaged_nature':2,

enc_label
0    2972
1    1418
2     515
3     385
4     349
5     240
Name: count, dtype: int64

In [15]:
dt["image_path"] = dt["image_path"].apply(
    lambda x: os.path.join(data_path, x).replace("\\", "/")
)
dt.head()

,label,image_path,post_text,enc_label
0,fires,data/damage_dataset/fires/images/forrestfire_2...,#fire #tornado #firetornado #forrestfire,4
1,fires,data/damage_dataset/fires/images/buildingfire_...,"Apartment fire in Harlem, NYC. \n#newyorkcity ...",4
2,fires,data/damage_dataset/fires/images/forrestfire_2...,Forrest fires=emergency runs to Wyoming to get...,4
3,fires,data/damage_dataset/fires/images/buildingfire_...,Glowing tin on the side of a garden shed at a ...,4
4,fires,data/damage_dataset/fires/images/buildingfire_...,My building is on fire.\n#mydubai\n#palmjumeir...,4

In [16]:
train_data, test_data = train_test_split(dt, test_size=0.1, random_state=42)
train_df, val_data =  train_test_split(train_data, test_size=0.1, random_state=42)

In [17]:
train_df.info()
train_df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 4761 entries, 3295 to 5643
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   label       4761 non-null   object
 1   image_path  4761 non-null   object
 2   post_text   4729 non-null   object
 3   enc_label   4761 non-null   int64
dtypes: int64(1), object(3)
memory usage: 186.0+ KB

,label,image_path,post_text,enc_label
3295,non_damage,data/damage_dataset/non_damage/images/ad_2017-...,How gorgeous are my sunnies from Diff Eyewear?...,0
3729,non_damage,data/damage_dataset/non_damage/images/ad_2017-...,#ootd Wearing my shorts today from @nordstrom ...,0
3571,non_damage,data/damage_dataset/non_damage/images/building...,Reflection\n.\n.\n.\n#moshing86 #indonesia #jo...,0
1515,damaged_infrastructure,data/damage_dataset/damaged_infrastructure/ima...,#زلزله_حلبچه\nتخریب ساختمان های مسکن مهر در زل...,1
5810,human_damage,data/damage_dataset/human_damage/images/isiscr...,Can we describe the pain of this injured Syria...,5

In [18]:
val_data.info()
val_data.head()

<class 'pandas.core.frame.DataFrame'>
Index: 530 entries, 2732 to 5256
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   label       530 non-null    object
 1   image_path  530 non-null    object
 2   post_text   523 non-null    object
 3   enc_label   530 non-null    int64
dtypes: int64(1), object(3)
memory usage: 20.7+ KB

,label,image_path,post_text,enc_label
2732,non_damage,data/damage_dataset/non_damage/images/ad_2017-...,محمد غريب راك بايكر \n#الإمارات #السعودية #الك...,0
1983,damaged_infrastructure,data/damage_dataset/damaged_infrastructure/ima...,La foto que marcó el antes y el después (versi...,1
5309,flood,data/damage_dataset/flood/images/hurricanesand...,It's been 5 years since hurricane sandy#hurric...,3
347,fires,data/damage_dataset/fires/images/buildingfire_...,#TBT From Chief Cliff Sligar (WFD Retired): Ja...,4
200,fires,data/damage_dataset/fires/images/forrestfire_2...,#forrestfire #fire #clearing\nclearing the are...,4

In [19]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 588 entries, 5370 to 1231
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   label       588 non-null    object
 1   image_path  588 non-null    object
 2   post_text   579 non-null    object
 3   enc_label   588 non-null    int64
dtypes: int64(1), object(3)
memory usage: 23.0+ KB

In [20]:
train_df.to_csv("data/damage_dataset/train_data.csv", index=False)
val_data.to_csv("data/damage_dataset/val_data.csv", index=False)
test_data.to_csv("data/damage_dataset/test_data.csv", index=False)

# CrisisMMD